project_id = "tahusvkrzaijcywuivle"

[api]
enabled = true
schemas = ["public", "storage"]

[db]
port = 54322
major_version = 15

[studio]
enabled = true

[auth]
enabled = true
site_url = "https://crm.tomekniedzwiecki.pl"
additional_redirect_urls = ["https://crm.tomekniedzwiecki.pl/zwolnie/login"]
jwt_expiry = 3600
enable_signup = false
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = false
