-- =============================================
-- DEPRECATED — superseded by 20260508_use_vault_for_cron_auth.sql
-- =============================================
--
-- Pierwotna treść tej migracji zawierała hardcoded JWT service_role,
-- co wykrył GitHub Secret Scanning (commit 6c88be7, 2026-05-08).
-- Token został zrotowany w Supabase Dashboard, a cron jobs przepięte
-- na Supabase Vault — patrz 20260508_use_vault_for_cron_auth.sql.
--
-- Ten plik zachowany jako placeholder dla porządku w historii migracji.
-- Nie zawiera wykonywalnego SQL — cron jobs ('manus-auto-reports',
-- 'manus-check-pending') są re-scheduled w 20260508.
--
-- =============================================
SELECT 1;  -- no-op
