-- 20260723c_wfp_v3_seed_fal.sql — Prospektor v3: seed 38 nowych nisz + plan fal prospectingu
-- Źródło: research GPT (gpt-5.6-sol + web_search, 4 kąty, 23.07.2026) → dedup vs 102 istniejące
-- → 38 najlepszych. Dwa klastry-dźwignie: (1) serwis techniczny z paszportem egzemplarza
-- i kalendarzem terminów (jeden rdzeń, reskin per wertykal), (2) compliance zawodów
-- regulowanych z nowym prawem 2025-26 (AML, KRAZ, kaucja, PPWR, UE najem krótki).
-- Fale: 1 = start (VIII-IX 2026, 6 wertykali, 6 kategorii), 2 = po wnioskach z fali 1 (9),
-- 3 = później, NULL = bez przydziału (P1-P2 + NO_GO po raporcie). Idempotentne.

-- ── 1. Seed 38 nowych nisz. ON CONFLICT DO NOTHING — nie ruszamy istniejących. ──
-- Nowe kategorie: Serwis techniczny i instalacje / Nieruchomości i administracja /
-- Zawody regulowane i finanse. Klaster inspekcyjny dołącza do istniejącej kategorii
-- „Bezpieczeństwo i compliance". Sezonowość zapisana w saturation_note.
INSERT INTO public.wfp_verticals (key, name, category, priority, operator_persona, pain, wedge_hint, saturation_note) VALUES
-- Serwis techniczny i instalacje (klaster: paszport egzemplarza + kalendarz terminów)
('serwis-chlodnictwa-fgaz','Serwis chłodnictwa komercyjnego / F-gaz','Serwis techniczny i instalacje',4,'Właściciel 2-8-os. serwisu chłodniczego obsługującego sklepy, gastronomię, magazyny','Kontrole szczelności, ilość czynnika i wpisy do CRO dla setek agregatów rozproszone między papierem, Excelem i CRO','Auto-kalendarz kontroli szczelności liczony z rodzaju/ilości czynnika + mobilny protokół + gotowa paczka do wpisu w CRO','Montero, Relup, iService, Locatick (generyczne field-service); CRO=gov; nowe przepisy F-gaz rozszerzają zakres'),
('serwis-wag-legalizacja','Serwis i legalizacja wag (metrologia)','Serwis techniczny i instalacje',4,'Metrolog / były serwisant producenta prowadzący lokalny serwis wag','Wagi handlowe/magazynowe/przemysłowe mają cykliczne terminy legalizacji, plomby, świadectwa; klient widzi koniec ważności dopiero przed kontrolą','Paszport metrologiczny urządzenia auto-składający protokół, świadectwo i termin następnej legalizacji w pakiet dla klienta','Brak dedykowanego SaaS; Excel/ERP/generyczne FSM'),
('serwis-oczyszczalni-przydomowych','Serwis przydomowych oczyszczalni ścieków','Serwis techniczny i instalacje',5,'Lokalny instalator budujący powtarzalny przychód serwisowy z własnej bazy montaży','Instalator traci kontakt po montażu, choć oczyszczalnia wymaga przeglądów, wywozu osadu, kontroli dmuchawy i dokumentów do kontroli gminy','Paszport oczyszczalni przekazywany właścicielowi po montażu — baza instalacji zamienia się w cykliczny kalendarz serwisów i wywozów','Brak dedykowanego; generyczne CRM/field-service'),
('serwis-uzdatniania-wody','Serwis systemów uzdatniania wody','Serwis techniczny i instalacje',4,'Mały instalator sanitarny / sprzedawca filtrów z portfelem kilkuset instalacji','Wymiany wkładów, sól, dezynfekcja, regeneracja złóż dla setek zmiękczaczy/filtrów/RO pilnowane ręcznie','Kalendarz serwisowy z typu urządzenia i zużycia wody + 1 klik do zamówienia właściwego kompletu materiałów','Apki producentów (MyDafi, Waters); brak niezależnego systemu wielu marek'),
('serwis-fotowoltaiki','Serwis instalacji PV (posprzedażowy)','Serwis techniczny i instalacje',4,'Były monter/kierownik ekip PV, który przeszedł na niezależny serwis wielu marek','Po boomie rośnie liczba instalacji do przeglądów/gwarancji, ale historia urządzeń zostaje u instalatora lub w mailach klienta','Cyfrowy paszport instalacji PV importowany ze zdjęć i faktur + termin przeglądu + raport serwisowy','Feldi, Locatick, Fieldworker (generyczne); monitoring falowników to nie proces serwisowy'),
('serwis-opomiarowania','Serwis ciepłomierzy / wodomierzy / podzielników','Serwis techniczny i instalacje',4,'Kierownik małej firmy montersko-odczytowej dla wspólnot/spółdzielni/zarządców','Tysiące liczników w budynkach z różnymi terminami legalizacji i dostępnością lokatorów; nieudana akcja = powtórne objazdy i reklamacje wspólnot','Kampania wymiany w budynku: umawianie lokatorów na sloty + zamknięcie kompletności całego pionu/nieruchomości','Brak dedykowanego dla małych wykonawców; systemy producentów liczników'),
('serwis-aparatury-medycznej','Serwis aparatury medycznej i laboratoryjnej','Serwis techniczny i instalacje',3,'Niezależny inżynier biomedyczny / właściciel małego pogwarancyjnego serwisu','Dziesiątki urządzeń z osobnymi paszportami i terminami; serwis ręcznie odtwarza historię i protokoły PN-EN 62353 (dot. też sprzętu dentystycznego i autoklawów)','Cyfrowy paszport urządzenia po QR: historia pomiarów, termin przeglądu, protokół podpisywany na miejscu','MMEwidencja NOVA, XEMI, CareControl po stronie placówki; strona serwisu cienka'),
('serwis-basenow','Serwis basenów i technologii basenowej','Serwis techniczny i instalacje',3,'Instalator basenów rozwijający abonamentowy serwis kilkudziesięciu obiektów','Otwarcia/zamknięcia kumulują się w kilka tygodni; serwis musi pamiętać konfigurację instalacji, chemię, kolejność zaworów, zdjęcia stanu każdego obiektu','Procedura sezonowa basenu: checklista z konfiguracji konkretnej instalacji + dawki chemii + potrzebne części','Generyczne field-service, Feldi, Locatick; sezonowy (piki wiosna/jesień)'),
-- Bezpieczeństwo i compliance (klaster: inspekcje z terminem ważności)
('przeglady-regalow','Przeglądy regałów magazynowych','Bezpieczeństwo i compliance',4,'Doświadczony monter/inspektor regałów obsługujący magazyny niezależnie','Inspektor dokumentuje tysiące słupów/trawersów/uszkodzeń na planach magazynu, potem ręcznie śledzi naprawy i coroczne terminy','Mobilna mapa magazynu: uszkodzenie na konkretnym elemencie + zdjęcie + auto-status zielony/pomarańczowy/czerwony','PRSES Inspect, Playmatec pokrewne; reszta PDF/generyczne inspection'),
('inspekcje-placow-zabaw','Inspekcje placów zabaw i siłowni plenerowych','Bezpieczeństwo i compliance',4,'Solo-inspektor bezpieczeństwa placów zabaw / mały wykonawca montujący urządzenia','Kontrole rutynowe/funkcjonalne/roczne dla gmin, wspólnot, przedszkoli; zdjęcia usterek i normy ręcznie składane w raporty','Inspekcja urządzenia po QR z checklistą zależną od typu sprzętu + porównanie zdjęcia usterki przed/po naprawie','Playmatec; reszta Excel/generyczne inspection'),
('przeglady-sprzetu-wysokosciowego','Przeglądy sprzętu chroniącego przed upadkiem (PPE)','Bezpieczeństwo i compliance',5,'Instruktor pracy na wysokości / były specjalista dostawcy sprzętu na własnych inspekcjach','Uprzęże, linki, urządzenia samohamowne, punkty kotwiczące mają osobne numery i terminy; karty sprzętu wciąż w segregatorach (dot. też drabin/podestów i zawiesi)','Skan QR/NFC — natychmiast status dopuszczenia, historia oględzin, powód wycofania; blokada dopuszczenia po terminie','Scafftag/Laddertag = tylko tagi; brak silnego SaaS PL'),
('monitoring-legionella','Monitoring i badania Legionella w budynkach','Bezpieczeństwo i compliance',4,'Ekspert instalacji wodnych/higieny lub lab uruchamiający wyspecjalizowaną usługę abonamentową','Plany poboru próbek, punkty czerpalne, wyniki lab, działania naprawcze i rebadania w wielu hotelach/DPS/szpitalach/obiektach sportowych','Mapa instalacji z punktami poboru auto-układająca harmonogram badań + workflow działań naprawczych po przekroczeniu','LIMS obsługuje próbki, nie portfel obiektów i działań naprawczych'),
('pomiary-srodowiska-pracy','Pomiary środowiska pracy (lab terenowe)','Bezpieczeństwo i compliance',3,'Były pracownik lab akredytowanego prowadzący własną małą ekipę pomiarową','Częstotliwości pomiarów hałasu/pyłów/drgań/chemii pilnowane osobno dla każdego stanowiska; sprawozdania i przypomnienia ręcznie','Matryca stanowisko-czynnik auto-wyznaczająca termin następnego pomiaru i zakres zlecenia z ostatniego wyniku','LIMS/generyczne systemy lab; brak lekkiego SaaS dla ekip terenowych'),
('audyty-higieny-zywnosci','Audyty higieny i badania mikrobiologiczne żywności','Bezpieczeństwo i compliance',3,'Technolog żywności / były inspektor jakości z małą firmą audytową współpracującą z lab','Doradca/lab cyklicznie pobiera wymazy i próbki, pilnuje planów HACCP i działań korygujących w wielu lokalach; wyniki w osobnych PDF','Plan poboru przypisany do punktów na planie zakładu — po wyniku auto-otwiera działanie korygujące i termin rebadania','HACCP Pilot/POLHACCP (lokal), LIMS (lab); brak wspólnego workflow usługodawca-klient'),
-- Produkcja i rzemiosło (klaster: akceptacja wersji przed produkcją)
('szklo-na-wymiar','Zakłady szklarskie / szkło na wymiar','Produkcja i rzemiosło',5,'Właściciel rodzinnego zakładu (kabiny, lustra, balustrady, szkło kuchenne)','Pomiary, rysunki, rodzaj szkła, obróbki, otwory krążą w zdjęciach i wiadomościach; pomyłka wersji = drogi element od nowa','Karta tafli z wymiarowanym rysunkiem + 1 przycisk akceptacji wersji przez klienta PRZED produkcją; kontrola jednostek/tolerancji','MonitGlass; CAD/ERP dla większych producentów'),
('szyldy-reklamy-swietlne','Pracownie szyldów, kasetonów, reklam świetlnych','Produkcja i rzemiosło',4,'Właściciel małej pracowni reklamy wizualnej z ploterem/frezarką/montażem','Jedno zlecenie ma wiele wizualizacji/wymiarów/wariantów podświetlenia; klient akceptuje inną wersję niż ta na produkcji','Portal akceptacji makiety na zdjęciu elewacji zamrażający zatwierdzoną wersję jako jedyny plik produkcyjny','iwarePrint/PrintFlow częściowo; brak dominującego dedykowanego'),
('haft-nadruki-odziez','Hafciarnie / znakowanie odzieży','Produkcja i rzemiosło',4,'Właściciel małej hafciarni/drukarni odzieżowej dla firm, klubów, szkół','Rozmiary, sztuki, kolory, techniki i wersje logo w arkuszach i wiadomościach; łatwo pomylić wariant w partii','Interaktywna matryca sztuka-rozmiar-kolor-nadruk z akceptacją próbki i zamrożeniem specyfikacji partii','iwarePrint częściowo; brak dla mikrohafciarni'),
('grawer-personalizacja','Grawernie / personalizacja laserowa','Produkcja i rzemiosło',4,'Właściciel pracowni laserowej (tabliczki, prezenty, identyfikatory, krótkie serie B2B)','Treści personalizacji dla wielu sztuk w mailach/Excelu; literówka lub zły egzemplarz = reklamacja całej partii','Walidator personalizacji per egzemplarz: klient zatwierdza podgląd każdej treści — zamknięta kolejka produkcyjna','Gravostyle steruje maszyną, nie obiegiem zlecenia'),
('drukarnie-etykiet-opakowania','Drukarnie etykiet i opakowań (krótkie serie)','Produkcja i rzemiosło',4,'Technolog/właściciel lokalnej drukarni cyfrowej obsługującej setki małych marek','Wiele wersji projektu/materiału/oznaczeń; trzeba udowodnić, która wersja i surowiec trafiły do partii; PPWR od 12.08.2026 podnosi wagę danych o materiale/recyklingu','Akceptacja zgodności przed drukiem: klient zatwierdza wersję etykiety z materiałem, ostrzeżeniami i deklaracjami opakowania','iwarePrint, PrintVis, ERP prepress; brak lekkiego SaaS; PPWR = świeży ból'),
('konserwacja-obiektow','Konserwacja dzieł sztuki, antyków, zabytków','Produkcja i rzemiosło',4,'Samodzielny konserwator / mała pracownia (kolekcjonerzy, parafie, instytucje)','Każdy obiekt wymaga protokołu stanu, obszernej dokumentacji foto, etapów prac i zatwierdzania zmian zakresu — w folderach, Wordzie, mailach','Chronologiczna karta konserwatorska generująca dokumentację przed/w trakcie/po bez ręcznego układania zdjęć','Brak dedykowanego SaaS PL'),
('hydraulika-silowa-regeneracja','Regeneracja hydrauliki siłowej','Produkcja i rzemiosło',4,'Właściciel warsztatu regeneracji siłowników/pomp/rozdzielaczy (budownictwo, rolnictwo, przemysł)','Siłownik/pompa trafia do rozbiórki bez identyfikacji, po której zmienia się zakres i cena; części i ustalenia trudno powiązać z podzespołem','Karta podzespołu z trwałym kodem, zdjęciami po rozbiórce i akceptacją kosztorysu regeneracji PRZED zamówieniem części','Brak dedykowanego dla małych; Integra Serwis/FSM'),
('przezwajanie-silnikow','Przezwajanie silników / regeneracja pomp','Produkcja i rzemiosło',3,'Elektromechanik prowadzący mały zakład przezwajania i napraw pomp','Podobne silniki/pompy bez historii parametrów, uzwojenia, części i prób; klient oczekuje szybkiej decyzji po diagnozie','Cyfrowa metryka egzemplarza z przyjęcia, parametrów uzwojenia i końcowego protokołu testowego','Brak dedykowanego SaaS; generyczne serwisowe/ERP'),
('wyroby-ortopedyczne-na-miare','Pracownie zaopatrzenia ortopedycznego na miarę','Produkcja i rzemiosło',3,'Technik ortopeda z małą pracownią (wkładki, ortezy, protezy, obuwie)','Skan/odlew, zalecenie, projekt, poprawki po przymiarce i wydanie w osobnych teczkach; e-zlecenie NFZ nie pokrywa procesu wykonawczego','Oś wykonania wyrobu łącząca skan, projekt, przymiarki, korekty i potwierdzenie wydania pacjentowi','NFZ e-zlecenie=refundacja; Posturologia.pl (wkładki) częściowo; proces wykonawczy = gap'),
-- Nieruchomości i administracja
('zarzadzanie-najmem-dlugoterminowy','Firmy zarządzające najmem mieszkań','Nieruchomości i administracja',4,'Właściciel małej firmy zarządzającej kilkudziesięcioma mieszkaniami dla inwestorów','Przy zmianie najemcy ginie chronologia zdjęć, usterek, liczników, kluczy i potrąceń z kaucji — spory z najemcą i właścicielem','Mobilny protokół przejęcia/zdania lokalu z porównaniem zdjęć punkt po punkcie + auto-dossier potrąceń z kaucji','Rentumi, simpl.rent; moduł protokół/kaucja cienki'),
('zarzadcy-najmu-krotkiego','Operatorzy najmu krótkoterminowego','Nieruchomości i administracja',4,'Były city manager / operator 10-80 apartamentów sfrustrowany Excelem i zmianami prawa','Rejestracja lokali, numery obiektów, wymogi ppoż/sanit, regulaminy i zgodność ogłoszeń na wielu platformach; unijne zasady udostępniania danych od 20.05.2026','Paszport zgodności lokalu: 1 karta pilnująca numeru rejestracyjnego, dokumentów, terminów i publikacji poprawnego numeru we wszystkich kanałach','IdoBooking, Hotres, KWHotel = rezerwacje/channel; compliance gap; UE 2026 = świeży ból'),
('facility-management-mikro','Mikrofirmy facility management','Nieruchomości i administracja',4,'Były techniczny zarządca prowadzący małą firmę FM dla kilku budynków','Obowiązki z umów najmu/polis/przeglądów/decyzji o różnych cyklach pilnowane w Excelu i kalendarzu','Macierz obowiązków obiektu auto-wyliczająca terminy + kompletny dowód wykonania każdego obowiązku dla właściciela','Singu FM, Planon, Archibus dla dużych portfeli; mikro cienki'),
-- Zawody regulowane i finanse
('posrednicy-nieruchomosci-aml','Biura pośrednictwa nieruchomości — AML','Zawody regulowane i finanse',4,'Samodzielny pośrednik / właściciel biura 2-5 agentów odpowiadający sam za AML','Dla transakcji trzeba dokumentować identyfikację klienta/beneficjenta, ocenę ryzyka, PEP, sankcje; CRM-y skupiają się na ofertach','Generator teczki AML transakcji: KYC + ocena ryzyka + wyniki sprawdzeń + uzasadnienie w 1 audytowalny PDF','ASARI/IMO/Virgo=oferty; iAML/SystemAML osobno; teczka transakcji=gap; presja egzekwowania AML'),
('agencje-zatrudnienia-kraz','Agencje zatrudnienia (KRAZ) / pracy tymczasowej','Zawody regulowane i finanse',4,'Właściciel małej agencji rekrutacji/pracy tymczasowej dla jednej branży/regionu','Dane o skierowaniach/zatrudnieniach/cudzoziemcach do sprawozdawczości KRAZ zbierane osobno od ATS; nowe obowiązki jawności płac od 24.12.2025','Licznik KRAZ zapisujący przy każdym kandydacie zdarzenie sprawozdawcze + karta zgodności skierowania blokująca zmianę przy braku dokumentu/stawki','HRappka, Traffit, enova = ATS; sprawozdawczość KRAZ = gap'),
('agencje-ochrony','Małe agencje ochrony fizycznej / imprez','Zawody regulowane i finanse',4,'Były kierownik/dowódca zmiany prowadzący lokalną agencję kilkunastu-kilkudziesięciu osób','Obsada wymaga pilnowania list kwalifikowanych, badań, szkoleń, pozwoleń; w sezonie imprez trzeba w kilka dni zebrać kwalifikowaną obsadę i udokumentować obecność','Silnik dopuszczenia pracownika do posterunku blokujący grafik przy braku/wygaśnięciu wymaganego dokumentu lub niepokryciu planu zabezpieczenia','Generyczne workforce/guard-tour; brak lekkiego lidera compliance PL'),
-- Usługi profesjonalne
('biegli-sadowi','Biegli sądowi (praktyka indywidualna)','Usługi profesjonalne',4,'Doświadczony specjalista pracujący jako jednoosobowy biegły dla kilku sądów','Postanowienia, akta, terminy opinii, wezwania, ewidencja godzin i rachunki z wielu sądów różnymi kanałami; przekroczenie terminu szkodzi reputacji','Rejestr zleceń sądowych odczytujący z postanowienia termin/pytania/zakres — po zakończeniu generuje zgodny rachunek z ewidencji pracy','OPINIA (ekspertyzy techniczne) niszowo; brak systemu operacyjnego dla biegłych'),
('mediatorzy-sadowi','Stali mediatorzy / centra mediacji','Usługi profesjonalne',3,'Aktywny mediator (praktyka jednoosobowa / małe centrum) obsługujący kilka sądów','Równoległe sprawy z różnych sądów i od klientów prywatnych: terminy, bezstronność, zgody, protokoły, ugody, poufny obieg dokumentów','Kreator teczki mediacji generujący z 1 przebiegu zaproszenia, zgody, protokół, projekt ugody i pakiet zwrotny do sądu','Brak dedykowanego SaaS; generyczne kancelaryjne/kalendarze'),
('swiadectwa-audyty-energetyczne','Świadectwa i audyty energetyczne budynków','Usługi profesjonalne',3,'Solo-inżynier / małe biuro seryjnie wykonujące świadectwa i audyty','Obliczenia w programie i rejestrze gov, ale zebranie danych wejściowych/zdjęć/rzutów/oświadczeń od klienta wciąż mailem; audyt do dotacji wymaga wielu wersji i załączników','Portal zlecenia sprawdzający kompletność danych PRZED obliczeniami + checklista kompletności audytu zależna od programu finansowania','ArCADia-TERMOCAD, Audytor OZC = obliczenia; CRCEB gov; intake/kompletność = gap; EPBD/dotacje 2026'),
('pracownie-architektoniczne','Pracownie architektoniczne (formalności)','Usługi profesjonalne',3,'Architekt prowadzący pracownię 1-5 os. samodzielnie koordynujący formalności','Mapy, warunki, uzgodnienia branżowe, decyzje i poprawki urzędu do skoordynowania; e-Budownictwo obsługuje złożenie, nie przygotowanie kompletnego pakietu','Mapa zależności formalnych projektu pokazująca brakujące uzgodnienia + auto-aktualizacja terminów po każdym wezwaniu urzędu','e-Budownictwo/SOPAB (gov); BIM/PM generyczny; koordynacja formalności = gap'),
-- Logistyka i handel
('operatorzy-vendingu','Operatorzy automatów vendingowych','Logistyka i handel',4,'Właściciel regionalnej firmy z 30-300 automatami w biurach/szkołach/zakładach','Rozwóz i rozliczenie na setkach maszyn; system kaucyjny od 1.10.2025 komplikuje ceny, ewidencję opakowań i rozrachunki kaucji','Rozliczenie kaucji per automat i trasa: porównanie zatowarowania, sprzedaży i należnej kaucji bez przebudowy telemetrii','Nayax/Televend = telemetria; kaucja = gap i świeży ból'),
('przewoznicy-autokarowi','Przewoźnicy autokarowi / wynajem autobusów','Logistyka i handel',4,'Właściciel 2-10 autokarów sam sprzedający przejazdy i układający grafik','Wycieczki/wesela/wakacje = ostre piki; jedna realizacja wymaga pojazdu, kierowców, czasu pracy, listy pasażerów, parkingów i częstych zmian godzin','Karta wyjazdu grupowego udostępniana 1 linkiem kierowcy/organizatorowi/opiekunom z zawsze aktualną godziną, miejscem i numerem autokaru','Softra, fireTMS = TMS; brak prostego produktu dla mikroprzewoźników grupowych'),
-- Budownictwo i dom / Turystyka / Rolnictwo i zieleń
('oslony-okienne-markizy','Producenci/monterzy rolet, żaluzji, markiz, pergoli','Budownictwo i dom',4,'Właściciel lokalnej firmy mierzącej/produkującej/montującej osłony i markizy na wymiar','Pomiar robi monter, wycenę biuro, produkcję warsztat; ręczne przepisywanie wymiarów i wariantów = pomyłki i powtórne wizyty','Mobilny protokół pomiarowy, który po podpisie klienta staje się nieedytowalną kartą produkcyjną i montażową','Stolcad Professional, VINCENT dla producentów; mikro pomiar-produkcja = gap; sezonowy (szczyt wiosna-lato)'),
('kempingi-camper-parki','Kempingi, camper parki, pola namiotowe','Turystyka',3,'Właściciel rodzinnego pola / manager małego camper parku w miejscowości turystycznej','W wakacyjne weekendy trzeba na jednej mapie upchnąć kampery/przyczepy/namioty o różnych wymiarach, pilnując prądu, sanitariatów, przyjazdów bez rezerwacji','Tetris parcelowy: auto-rozmieszczenie rezerwacji wg wymiarów zestawu i infrastruktury, minimalizujące luki','Connect Camp, KWHotel; zagraniczne PMS kempingowe; sezonowy (lato)'),
('zimowe-utrzymanie','Firmy zimowego utrzymania terenów','Rolnictwo i zieleń',3,'Właściciel kilku pługopiaskarek / firmy łączącej sezonowo utrzymanie terenów','Przy opadach wszystkie kontrakty ruszają naraz; trzeba dysponować pojazdy wg priorytetów i udowodnić klientowi godzinę przejazdu, posypania i zużycie materiału','Dowód wykonania kontraktu: auto-oś czasu z GPS, zdjęciami przed/po i warunkami pogodowymi dla każdego obiektu','Generyczne GPS/TMS/field-service; brak lidera wertykalnego; sezonowy (zima; sprzedaż VIII-XI)')
ON CONFLICT (key) DO NOTHING;

-- ── 2. Plan fal prospectingu (kolejność odzywania się — nie da się do wszystkich naraz) ──
-- FALA 1 — start VIII-IX 2026: 6 wertykali, 6 różnych kategorii, sezonowość neutralna,
-- persona osiągalna mailem, niska saturacja.
UPDATE public.wfp_verticals SET wave = 1 WHERE key IN (
  'firmy-ddd','szklo-na-wymiar','serwis-oczyszczalni-przydomowych',
  'asenizacja','biegli-sadowi','cukiernie-torty'
);

-- FALA 2 — po wnioskach z fali 1: dywersyfikacja + świeżość prawna + okna sezonowe
-- (zimowe-utrzymanie sprzedaje się PRZED zimą, osłony/DJ-e po sezonie). Część report-first:
-- monitoring-legionella, posrednicy-nieruchomosci-aml, bhp-outsourcing — najpierw raport wedge.
UPDATE public.wfp_verticals SET wave = 2 WHERE key IN (
  'pracownie-protetyczne','serwis-fotowoltaiki','monitoring-legionella',
  'posrednicy-nieruchomosci-aml','operatorzy-vendingu','zespoly-dj-weselni',
  'oslony-okienne-markizy','zimowe-utrzymanie','bhp-outsourcing'
);

-- FALA 3 — reszta wartościowych (P3-P5); na początek fali: przeglady-sprzetu-wysokosciowego (P5).
UPDATE public.wfp_verticals SET wave = 3 WHERE key IN (
  -- nowe v3
  'serwis-chlodnictwa-fgaz','serwis-wag-legalizacja','serwis-uzdatniania-wody',
  'serwis-opomiarowania','serwis-aparatury-medycznej','serwis-basenow',
  'przeglady-regalow','inspekcje-placow-zabaw','przeglady-sprzetu-wysokosciowego',
  'pomiary-srodowiska-pracy','audyty-higieny-zywnosci','szyldy-reklamy-swietlne',
  'haft-nadruki-odziez','grawer-personalizacja','drukarnie-etykiet-opakowania',
  'konserwacja-obiektow','hydraulika-silowa-regeneracja','przezwajanie-silnikow',
  'wyroby-ortopedyczne-na-miare','zarzadzanie-najmem-dlugoterminowy','zarzadcy-najmu-krotkiego',
  'facility-management-mikro','agencje-zatrudnienia-kraz','agencje-ochrony',
  'mediatorzy-sadowi','swiadectwa-audyty-energetyczne','pracownie-architektoniczne',
  'przewoznicy-autokarowi','kempingi-camper-parki',
  -- istniejące z katalogu v2
  'stolarnia-na-wymiar','nadzor-budowlany','serwis-udt','wynajem-sprzetu-eventowego',
  'pielegnacja-zieleni','szkolki-roslin','kamieniarstwo','kominiarstwo','obozy-kolonie',
  'brukarstwo','dekarstwo','remonty-wykonczenia','bramy-ogrodzenia','instalacje-elektryczne',
  'projektowanie-wnetrz','przeglady-budynkow','studia-tatuazu','podologia','logopedia',
  'psychoterapia','przechowalnia-opon','laweta-pomoc-drogowa','detailing','geodeci',
  'fotografia-slubna','wedding-planner','wypozyczalnia-sukni','dmuchance-animatorzy',
  'kwiaciarnie','catering-eventowy','uslugi-rolnicze','pracownie-krawieckie','przeprowadzki',
  'odpady-bdo','pralnie','wypozyczalnie-sprzetu','serwis-gsm','szkoly-narciarskie',
  'wypozyczalnie-wodne','hotele-dla-zwierzat','piekarnie-rzemieslnicze',
  'organizatorzy-eventow-firmowych','serwis-kotlow-gazowych'
);

-- BEZ FALI (wave NULL, default): P1-P2 z katalogu ORAZ firmy-ppoz (raport NO_GO 12/24 —
-- świadoma decyzja po badaniu, możliwe re-badanie nowym promptem wedge-obok-lidera).
