-- ============================================================================
-- WORKFLOW APLIKACJE (wfa) — fundament (F1)
-- Moduł prowadzenia budowy aplikacji SaaS po pełnej płatności /aplikacja.
-- Plan: docs/stworze/WORKFLOW-APLIKACJE-PLAN.md
-- Fork wzorca wf2 (kroki = konfiguracja wfa_step_defs, instancje = wfa_steps,
-- jedno źródło postępu). Bez macierzy produktów — aplikacja = jedna encja.
-- ============================================================================

-- ── PROJEKTY (1 projekt = 1 aplikacja) ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.wfa_projects (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  name                 text NOT NULL DEFAULT '',            -- nazwa aplikacji (może być robocza)
  slug                 text UNIQUE,                          -- kebab: repo = Vercel = ref bazy = domena
  customer_name        text,
  customer_email       text,
  customer_phone       text,
  lead_id              uuid,                                 -- leads.id (luźno, bez FK)
  spar_session_id      uuid UNIQUE,                          -- spar_sessions.id — źródło danych wejściowych
  status               text NOT NULL DEFAULT 'fundament'
                       CHECK (status IN ('fundament','infrastruktura','budowa','jakosc','start','stery','zamkniety')),
  unique_token         text UNIQUE DEFAULT replace(gen_random_uuid()::text, '-', ''),
  client_password_hash text,
  -- infrastruktura SaaS
  domain               text,
  app_url              text,
  landing_url          text,
  repo_url             text,
  vercel_project       text,
  supabase_ref         text,
  -- płatności / rev-share (Stripe Connect: Standard + direct charges)
  stripe_account_id    text,                                 -- acct_… klienta-operatora
  fee_percent          numeric(5,2) NOT NULL DEFAULT 10.0,   -- % Tomka od przychodu (application fee)
  notes                text,
  is_test              boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS wfa_projects_session_idx ON public.wfa_projects(spar_session_id);
CREATE INDEX IF NOT EXISTS wfa_projects_status_idx  ON public.wfa_projects(status);

-- ── DEFINICJE KROKÓW (konfiguracja — nowy krok = 1 INSERT) ──────────────────
CREATE TABLE IF NOT EXISTS public.wfa_step_defs (
  key             text PRIMARY KEY,
  stage           integer NOT NULL,
  stage_label     text NOT NULL,
  label           text NOT NULL,
  icon            text NOT NULL DEFAULT 'ph-circle',
  sort            integer NOT NULL DEFAULT 0,
  owner           text NOT NULL DEFAULT 'admin' CHECK (owner IN ('admin','client','auto')),
  instructions_md text,                                     -- instrukcje dla klienta (portal, F3)
  milestone_label text,                                     -- jeśli ustawione: ukończenie = kamień milowy w portalu
  active          boolean NOT NULL DEFAULT true
);

-- ── INSTANCJE KROKÓW (jedyne źródło postępu) ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.wfa_steps (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id   uuid NOT NULL REFERENCES public.wfa_projects(id) ON DELETE CASCADE,
  step_key     text NOT NULL REFERENCES public.wfa_step_defs(key),
  status       text NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending','in_progress','done','skipped','blocked')),
  data         jsonb NOT NULL DEFAULT '{}'::jsonb,          -- notatki/linki/pola/checklisty kroku
  completed_at timestamptz,
  completed_by text,                                        -- 'admin' | 'client' | 'auto'
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (project_id, step_key)
);
CREATE INDEX IF NOT EXISTS wfa_steps_project_idx ON public.wfa_steps(project_id);

-- ── UWAGI TOMKA (wejście do paczek promptów; kind uwaga/decyzja/blokada) ────
CREATE TABLE IF NOT EXISTS public.wfa_notes (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id  uuid NOT NULL REFERENCES public.wfa_projects(id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  author      text NOT NULL DEFAULT 'tomek',
  kind        text NOT NULL DEFAULT 'uwaga' CHECK (kind IN ('uwaga','decyzja','blokada')),
  status      text NOT NULL DEFAULT 'open' CHECK (status IN ('open','done')),
  content     text NOT NULL DEFAULT '',
  resolved_at timestamptz
);
CREATE INDEX IF NOT EXISTS wfa_notes_project_idx ON public.wfa_notes(project_id, status);

-- ── LOG AKTYWNOŚCI ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.wfa_activities (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  uuid NOT NULL REFERENCES public.wfa_projects(id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  actor       text NOT NULL DEFAULT 'admin',                -- 'admin' | 'client' | 'auto'
  action      text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS wfa_activities_project_idx ON public.wfa_activities(project_id, created_at DESC);

-- ── updated_at ──────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.wfa_touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END $$;

DROP TRIGGER IF EXISTS wfa_projects_touch ON public.wfa_projects;
CREATE TRIGGER wfa_projects_touch BEFORE UPDATE ON public.wfa_projects
  FOR EACH ROW EXECUTE FUNCTION public.wfa_touch_updated_at();
DROP TRIGGER IF EXISTS wfa_steps_touch ON public.wfa_steps;
CREATE TRIGGER wfa_steps_touch BEFORE UPDATE ON public.wfa_steps
  FOR EACH ROW EXECUTE FUNCTION public.wfa_touch_updated_at();

-- ── ensure steps: dosiewa brakujące instancje (SECURITY DEFINER — UI i automaty) ─
CREATE OR REPLACE FUNCTION public.wfa_ensure_steps(p_project uuid) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO wfa_steps (project_id, step_key)
  SELECT p_project, d.key FROM wfa_step_defs d
  WHERE d.active
    AND NOT EXISTS (SELECT 1 FROM wfa_steps s
                    WHERE s.project_id = p_project AND s.step_key = d.key);
END $$;
GRANT EXECUTE ON FUNCTION public.wfa_ensure_steps(uuid) TO authenticated, service_role;

-- ── sync projektów: spar_sessions (full_paid, nie-test) → wfa_projects.
--    Wołane przy load panelu — celowo ZERO zmian w tpay-webhook/spar-chat. ───
CREATE OR REPLACE FUNCTION public.wfa_sync_projects() RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  r record;
  created integer := 0;
  new_id uuid;
BEGIN
  FOR r IN
    SELECT ss.id, ss.name, ss.email, ss.phone, ss.lead_id
    FROM spar_sessions ss
    WHERE ss.full_paid_at IS NOT NULL
      AND COALESCE(ss.is_test, false) = false
      AND NOT EXISTS (SELECT 1 FROM wfa_projects p WHERE p.spar_session_id = ss.id)
  LOOP
    INSERT INTO wfa_projects (name, customer_name, customer_email, customer_phone, lead_id, spar_session_id)
    VALUES ('', r.name, r.email, r.phone, r.lead_id, r.id)
    RETURNING id INTO new_id;
    PERFORM wfa_ensure_steps(new_id);
    INSERT INTO wfa_activities (project_id, actor, action, description)
    VALUES (new_id, 'auto', 'project_created', 'Auto-sync z spar_sessions (pełna płatność)');
    created := created + 1;
  END LOOP;
  RETURN created;
END $$;
GRANT EXECUTE ON FUNCTION public.wfa_sync_projects() TO authenticated, service_role;

-- ── RLS: tylko zespół (team_members) — ZERO polityk anon; portal klienta
--    pójdzie przez edge function wfa-portal (F3), nie przez anon RLS ─────────
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['wfa_projects','wfa_step_defs','wfa_steps','wfa_notes','wfa_activities']
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_team_all', t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL TO authenticated
       USING (EXISTS (SELECT 1 FROM team_members tm WHERE tm.user_id = auth.uid()))
       WITH CHECK (EXISTS (SELECT 1 FROM team_members tm WHERE tm.user_id = auth.uid()))',
      t || '_team_all', t);
  END LOOP;
END $$;

-- ── SEED: definicje kroków (etapy 1–5 wg WORKFLOW-APLIKACJE-PLAN.md §4) ─────
INSERT INTO public.wfa_step_defs (key, stage, stage_label, label, icon, sort, owner, instructions_md, milestone_label) VALUES
-- ETAP 1 — Fundament
('handoff',        1, 'Fundament',        'Handoff pack',              'ph-package',                10, 'admin',  NULL, NULL),
('zalaczniki',     1, 'Fundament',        'Materiały klienta',         'ph-paperclip',              20, 'client', 'Wgraj obiecane materiały (pliki, linki, dokumenty), które pomogą nam przy budowie aplikacji.', NULL),
('uwagi_tomka',    1, 'Fundament',        'Uwagi Tomka',               'ph-note-pencil',            30, 'admin',  NULL, NULL),
('mvp_scope',      1, 'Fundament',        'Definicja MVP',             'ph-target',                 40, 'admin',  NULL, NULL),
('nazwa',          1, 'Fundament',        'Nazwa aplikacji',           'ph-text-aa',                50, 'admin',  NULL, NULL),
('domena',         1, 'Fundament',        'Domena',                    'ph-globe',                  60, 'admin',  NULL, NULL),
('akcept_klienta', 1, 'Fundament',        'Akcept: MVP + nazwa',       'ph-check-circle',           70, 'client', 'Zatwierdź zakres pierwszej wersji aplikacji oraz jej nazwę — od tego momentu ruszamy z budową.', 'Zakres i nazwa aplikacji zatwierdzone'),
-- ETAP 2 — Infrastruktura
('repo_vercel',    2, 'Infrastruktura',   'Repo + Vercel',             'ph-git-branch',             10, 'admin',  NULL, NULL),
('supabase_proj',  2, 'Infrastruktura',   'Projekt Supabase',          'ph-database',               20, 'admin',  NULL, NULL),
('resend_dns',     2, 'Infrastruktura',   'Resend + DNS e-mail',       'ph-envelope',               30, 'admin',  NULL, NULL),
('stripe_kyc',     2, 'Infrastruktura',   'Stripe klienta (KYC)',      'ph-identification-card',    40, 'client', 'Załóż konto Stripe przez link, który od nas dostaniesz, i przejdź weryfikację (dane firmy, konto bankowe). To Twoje konto — na nie trafiają płatności użytkowników aplikacji.', NULL),
('stripe_plany',   2, 'Infrastruktura',   'Stripe: plany + % platformy','ph-credit-card',           50, 'admin',  NULL, NULL),
('env_secrets',    2, 'Infrastruktura',   'Env + sekrety',             'ph-key',                    60, 'admin',  NULL, 'Infrastruktura gotowa'),
-- ETAP 3 — Budowa MVP
('paczka_cc',      3, 'Budowa MVP',       'Paczka dla Claude Code',    'ph-magic-wand',             10, 'admin',  NULL, NULL),
('schemat_db',     3, 'Budowa MVP',       'Schemat DB + RLS',          'ph-table',                  20, 'admin',  NULL, NULL),
('auth_konta',     3, 'Budowa MVP',       'Auth + konta userów',       'ph-user-circle',            30, 'admin',  NULL, NULL),
('funkcja_glowna', 3, 'Budowa MVP',       'Funkcja główna',            'ph-lightning',              40, 'admin',  NULL, NULL),
('panel_usera',    3, 'Budowa MVP',       'Panel użytkownika',         'ph-layout',                 50, 'admin',  NULL, NULL),
('panel_operatora',3, 'Budowa MVP',       'Panel operatora',           'ph-gauge',                  60, 'admin',  NULL, NULL),
('platnosci_e2e',  3, 'Budowa MVP',       'Płatności Stripe E2E',      'ph-currency-circle-dollar', 70, 'admin',  NULL, NULL),
('maile_trans',    3, 'Budowa MVP',       'E-maile transakcyjne',      'ph-paper-plane-tilt',       80, 'admin',  NULL, 'Aplikacja działa (wersja robocza)'),
-- ETAP 4 — Landing i jakość
('landing',        4, 'Landing i jakość', 'Landing + cennik',          'ph-browser',                10, 'admin',  NULL, NULL),
('testy_e2e',      4, 'Landing i jakość', 'Testy przepływów',          'ph-flask',                  20, 'admin',  NULL, NULL),
('audyt',          4, 'Landing i jakość', 'Audyt bezpieczeństwa',      'ph-shield-check',           30, 'admin',  NULL, NULL),
('poprawki',       4, 'Landing i jakość', 'Poprawki po audycie',       'ph-wrench',                 40, 'admin',  NULL, 'Aplikacja przeszła audyt bezpieczeństwa'),
-- ETAP 5 — Start
('prawne',         5, 'Start',            'Regulamin + RODO + DPA',    'ph-scales',                 10, 'admin',  NULL, NULL),
('onboarding_op',  5, 'Start',            'Wdrożenie operatora',       'ph-graduation-cap',         20, 'client', 'Przejdź z nami onboarding z panelu operatora: obsługa użytkowników, płatności, statystyki.', NULL),
('start_live',     5, 'Start',            'START aplikacji',           'ph-rocket-launch',          30, 'admin',  NULL, 'Aplikacja wystartowała'),
('gtm_50',         5, 'Start',            'Droga do 50 klientów',      'ph-trend-up',               40, 'admin',  NULL, NULL),
('stery',          5, 'Start',            'Przekazanie sterów',        'ph-handshake',              50, 'admin',  NULL, 'Stery przekazane operatorowi')
ON CONFLICT (key) DO NOTHING;

COMMENT ON TABLE public.wfa_projects  IS 'Workflow Aplikacje: projekty budowy aplikacji SaaS (po pełnej płatności /aplikacja). Plan: docs/stworze/WORKFLOW-APLIKACJE-PLAN.md';
COMMENT ON TABLE public.wfa_step_defs IS 'Workflow Aplikacje: definicje kroków — nowy krok = INSERT (zero zmian schematu/frontu); milestone_label = kamień milowy dla portalu klienta';
COMMENT ON TABLE public.wfa_steps     IS 'Workflow Aplikacje: instancje kroków — JEDYNE źródło postępu projektu';
COMMENT ON TABLE public.wfa_notes     IS 'Workflow Aplikacje: uwagi/decyzje Tomka per projekt — wejście do paczek promptów Claude Code';
