-- ============================================================================
-- ZBUDUJĘ (sparing AWE) — F0: fundament danych (fork spar_* -> bud_*)
-- Pełna izolacja od działającej Aplikacji. Mirror schematu spar_* (stan live
-- 2026-06-21) z różnicami pod e-commerce + 3 kierunki (track k1/k2/k3).
-- Wzorzec RLS: gate team_members (admin) + owner (auth_user_id); BEZ polityk
-- anon/authenticated USING(true) — projekt dzielony z CRM (incydent 20260614).
-- Zapis treści sesji = wyłącznie service_role (edge bud-*). Panel pisze przez
-- kolumnowy GRANT UPDATE (jak spar_sessions). Idempotentne.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- A. TABELE
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.bud_sessions (
  id                        uuid PRIMARY KEY,                 -- klient generuje (brak DEFAULT zamierzony)
  -- pola wejścia / kontekst
  profession                text,                             -- relikt po spar (nieużywane w e-com, zostawione dla zgodności forka)
  problem_hint              text,                             -- podpowiedź startowa (np. z /zapisy tried[])
  email                     text,
  name                      text,
  status                    text NOT NULL DEFAULT 'active',
  verdict                   text,                             -- null / zielony / żółty / czerwony
  problem_summary           jsonb,                            -- karta projektu
  tracking                  jsonb,                            -- gclid/fbclid/utm z /zapisy
  lead_id                   uuid,
  turns                     integer NOT NULL DEFAULT 0,
  ip                        text,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),
  -- podgląd / makiety
  preview_brief             jsonb,
  preview_image_url         text,
  image_count               integer NOT NULL DEFAULT 0,
  preview_images            jsonb,                            -- {sklep, karta_produktu, logo, lifestyle, ...}
  preview_history           jsonb,
  business_plan             jsonb,                            -- prognoza przychodu e-com
  -- kontakt / auth
  phone                     text,
  auth_user_id              uuid,
  auth_provider             text,
  -- płatności
  paid_at                   timestamptz,                      -- rezerwacja 500 zł
  full_paid_at              timestamptz,                      -- pełna płatność budowy (-> know-how)
  knowhow_closed_at         timestamptz,
  -- pipeline / drip
  last_user_at              timestamptz,
  last_panel_at             timestamptz,
  panel_visits              integer NOT NULL DEFAULT 0,
  seen_landing_at           timestamptz,
  left_screen_at            timestamptz,
  left_screen               text,
  sequence_cancelled_at     timestamptz,
  pipeline_override         text,
  -- higiena / feed
  is_test                   boolean NOT NULL DEFAULT false,
  showcase                  boolean NOT NULL DEFAULT false,
  hidden_from_feed          boolean NOT NULL DEFAULT false,
  -- deliverables analityczne
  market_report             jsonb,
  landing_url               text,
  economics                 jsonb,
  gtm                       jsonb,
  assessment                jsonb,                            -- wynik bramki bud-assess
  -- SMS
  sms_consent_at            timestamptz,
  sms_opt_out               boolean NOT NULL DEFAULT false,
  -- dedup Slack
  slack_contact_notified_at timestamptz,
  slack_green_notified_at   timestamptz,
  slack_preview_notified_at timestamptz,
  -- locki / błędy / know-how
  gen_locks                 jsonb DEFAULT '{}'::jsonb,
  lead_error                text,
  idea_source               text NOT NULL DEFAULT 'wlasny',
  -- ===== RÓŻNICE AWE / 3 kierunki =====
  track                     text,                             -- k1 / k2 / k3
  niche                     text,                             -- wybrana / rekomendowana nisza-produkt
  product_input             jsonb,                            -- K2: {nazwa, zdjecia[], url, cena_obecna, kanal_sprzedazy}
  demand_validation         jsonb,                            -- wynik walidacji popytu
  brand                     jsonb,                            -- {nazwa, logo_url, paleta[], typografia, domena_pl}
  CONSTRAINT bud_sessions_idea_source_check CHECK (idea_source = ANY (ARRAY['wlasny','ai','wspolny'])),
  CONSTRAINT bud_sessions_track_check CHECK (track IS NULL OR track = ANY (ARRAY['k1','k2','k3']))
);

CREATE TABLE IF NOT EXISTS public.bud_messages (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id  uuid NOT NULL REFERENCES public.bud_sessions(id) ON DELETE CASCADE,
  role        text NOT NULL,
  content     text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  channel     text NOT NULL DEFAULT 'sparing',
  CONSTRAINT bud_messages_role_check CHECK (role = ANY (ARRAY['user','assistant']))
);

CREATE TABLE IF NOT EXISTS public.bud_usage (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id    uuid REFERENCES public.bud_sessions(id) ON DELETE CASCADE,
  kind          text NOT NULL,
  model         text,
  input_tokens  integer NOT NULL DEFAULT 0,
  cached_tokens integer NOT NULL DEFAULT 0,
  output_tokens integer NOT NULL DEFAULT 0,
  images        integer NOT NULL DEFAULT 0,
  cost_usd      numeric NOT NULL DEFAULT 0,
  meta          jsonb,
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bud_usage_kind_check CHECK (kind = ANY (ARRAY['chat','plan','image','landing','raport','prototype','economics','gtm','email','assess','brand','demand']))
);

CREATE TABLE IF NOT EXISTS public.bud_reveals (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id  uuid NOT NULL REFERENCES public.bud_sessions(id) ON DELETE CASCADE,
  key         text NOT NULL,
  seq         integer NOT NULL,
  due_at      timestamptz,
  status      text NOT NULL DEFAULT 'pending',
  generated_at timestamptz,
  sent_at     timestamptz,
  email_kind  text,
  meta        jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz,
  CONSTRAINT bud_reveals_status_check CHECK (status = ANY (ARRAY['pending','generating','ready','sent','paused','skipped'])),
  CONSTRAINT bud_reveals_session_id_key_key UNIQUE (session_id, key)
);

CREATE TABLE IF NOT EXISTS public.bud_emails (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id   uuid REFERENCES public.bud_sessions(id) ON DELETE CASCADE,
  kind         text NOT NULL,
  email        text NOT NULL,
  sent_at      timestamptz NOT NULL DEFAULT now(),
  resend_id    text,
  opened_at    timestamptz,
  clicked_at   timestamptz,
  delivered_at timestamptz,
  CONSTRAINT bud_emails_session_id_kind_key UNIQUE (session_id, kind)
);

CREATE TABLE IF NOT EXISTS public.bud_abandoned_emails (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id   uuid NOT NULL REFERENCES public.bud_sessions(id) ON DELETE CASCADE,
  kind         text NOT NULL,
  seq          integer NOT NULL,
  subject      text,
  html         text,
  sms          text,
  status       text NOT NULL DEFAULT 'pending',
  scheduled_at timestamptz,
  sent_at      timestamptz,
  resend_id    text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bud_abandoned_emails_session_id_kind_key UNIQUE (session_id, kind)
);

CREATE TABLE IF NOT EXISTS public.bud_sms (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id  uuid NOT NULL REFERENCES public.bud_sessions(id) ON DELETE CASCADE,
  kind        text NOT NULL,
  phone       text,
  message     text,
  smsapi_id   text,
  points      numeric,
  status      text,
  clicked_at  timestamptz,
  meta        jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  delivered_at timestamptz,
  dlr_status  text,
  dlr_at      timestamptz,
  CONSTRAINT bud_sms_session_id_kind_key UNIQUE (session_id, kind)
);

CREATE TABLE IF NOT EXISTS public.bud_short_links (
  code       text PRIMARY KEY,
  session_id uuid NOT NULL REFERENCES public.bud_sessions(id) ON DELETE CASCADE,
  clicks     integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bud_short_links_session_id_key UNIQUE (session_id)
);

CREATE TABLE IF NOT EXISTS public.bud_feedback (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id uuid NOT NULL REFERENCES public.bud_sessions(id) ON DELETE CASCADE,
  text       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.bud_knowhow_items (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id     uuid NOT NULL REFERENCES public.bud_sessions(id) ON DELETE CASCADE,
  lead_id        uuid REFERENCES public.leads(id) ON DELETE SET NULL,
  kind           text NOT NULL,
  source_tag     text NOT NULL DEFAULT 'klient',
  content        text NOT NULL,
  url            text,
  file_path      text,
  file_mime_type text,
  meta           jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by     uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  used_in_build  boolean NOT NULL DEFAULT false,
  used_at        timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  scope          text,
  CONSTRAINT bud_knowhow_items_kind_check CHECK (kind = ANY (ARRAY['wniosek','wymaganie','link','zalacznik','uwaga','cytat','intel_cenowy','luka','decyzja','sprzecznosc','zalozenie','dostawca','produkt','logistyka'])),
  CONSTRAINT bud_knowhow_items_source_tag_check CHECK (source_tag = ANY (ARRAY['klient','research'])),
  CONSTRAINT bud_knowhow_items_scope_check CHECK (scope IS NULL OR scope = ANY (ARRAY['v1','pozniej','poza','nieznane']))
);

CREATE TABLE IF NOT EXISTS public.bud_knowhow_summary (
  session_id              uuid PRIMARY KEY REFERENCES public.bud_sessions(id) ON DELETE CASCADE,
  lead_id                 uuid REFERENCES public.leads(id) ON DELETE SET NULL,
  status                  text NOT NULL DEFAULT 'active',
  closed_at               timestamptz,
  items_count             integer NOT NULL DEFAULT 0,
  wymagania_count         integer NOT NULL DEFAULT 0,
  zalaczniki_count        integer NOT NULL DEFAULT 0,
  summary_text            text,
  summary_ai_generated_at timestamptz,
  idea_source             text NOT NULL DEFAULT 'wlasny',
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  handoff_pack            text,
  handoff_generated_at    timestamptz,
  extract_error           text,
  extract_error_at        timestamptz,
  handoff_error           text,
  handoff_error_at        timestamptz,
  CONSTRAINT bud_knowhow_summary_status_check CHECK (status = ANY (ARRAY['active','closed'])),
  CONSTRAINT bud_knowhow_summary_idea_source_check CHECK (idea_source = ANY (ARRAY['wlasny','ai','wspolny']))
);

-- ----------------------------------------------------------------------------
-- B. INDEKSY
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_bud_messages_session    ON public.bud_messages(session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_bud_usage_session       ON public.bud_usage(session_id);
CREATE INDEX IF NOT EXISTS idx_bud_usage_created       ON public.bud_usage(created_at);
CREATE INDEX IF NOT EXISTS idx_bud_reveals_session     ON public.bud_reveals(session_id);
CREATE INDEX IF NOT EXISTS idx_bud_reveals_due         ON public.bud_reveals(status, due_at);
CREATE INDEX IF NOT EXISTS idx_bud_sessions_verdict    ON public.bud_sessions(verdict);
CREATE INDEX IF NOT EXISTS idx_bud_sessions_track      ON public.bud_sessions(track);
CREATE INDEX IF NOT EXISTS idx_bud_sessions_auth_user  ON public.bud_sessions(auth_user_id);
CREATE INDEX IF NOT EXISTS idx_bud_sessions_lead       ON public.bud_sessions(lead_id);
CREATE INDEX IF NOT EXISTS idx_bud_knowhow_items_sess  ON public.bud_knowhow_items(session_id);

-- ----------------------------------------------------------------------------
-- C. TRIGGER updated_at
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.bud_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN NEW.updated_at := now(); RETURN NEW; END;
$fn$;

DROP TRIGGER IF EXISTS trg_bud_sessions_updated_at ON public.bud_sessions;
CREATE TRIGGER trg_bud_sessions_updated_at BEFORE UPDATE ON public.bud_sessions
  FOR EACH ROW EXECUTE FUNCTION public.bud_set_updated_at();

DROP TRIGGER IF EXISTS trg_bki_upd ON public.bud_knowhow_items;
CREATE TRIGGER trg_bki_upd BEFORE UPDATE ON public.bud_knowhow_items
  FOR EACH ROW EXECUTE FUNCTION public.bud_set_updated_at();

DROP TRIGGER IF EXISTS trg_bks_upd ON public.bud_knowhow_summary;
CREATE TRIGGER trg_bks_upd BEFORE UPDATE ON public.bud_knowhow_summary
  FOR EACH ROW EXECUTE FUNCTION public.bud_set_updated_at();

-- ----------------------------------------------------------------------------
-- D. RPC (SECURITY DEFINER + search_path; mirror spar_*)
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.bud_claim_lock(p_session uuid, p_key text, p_ttl_sec integer)
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path TO 'public' AS $fn$
  UPDATE bud_sessions
  SET gen_locks = COALESCE(gen_locks, '{}'::jsonb) || jsonb_build_object(p_key, now()::text)
  WHERE id = p_session
    AND (gen_locks->>p_key IS NULL OR (gen_locks->>p_key)::timestamptz < now() - make_interval(secs => p_ttl_sec))
  RETURNING true;
$fn$;

CREATE OR REPLACE FUNCTION public.bud_release_lock(p_session uuid, p_key text)
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path TO 'public' AS $fn$
  UPDATE bud_sessions SET gen_locks = COALESCE(gen_locks, '{}'::jsonb) - p_key
  WHERE id = p_session RETURNING true;
$fn$;

-- Widoki NIE zużywające puli image_count (marka/extras): logo, lifestyle, telefon, podsumowanie, marka.
-- Pulę zużywają widoki edytowalne: sklep, karta_produktu (+ ewentualne kolejne ekrany).
CREATE OR REPLACE FUNCTION public.bud_record_image(p_session uuid, p_view text, p_url text)
RETURNS integer LANGUAGE sql SECURITY DEFINER SET search_path TO 'public' AS $fn$
  UPDATE bud_sessions
  SET image_count = COALESCE(image_count, 0) + CASE WHEN p_view IN ('podsumowanie','marka','logo','lifestyle','telefon') THEN 0 ELSE 1 END,
      preview_history = CASE
        WHEN preview_images ? p_view AND preview_images->>p_view IS NOT NULL AND preview_images->>p_view <> p_url
        THEN jsonb_set(COALESCE(preview_history, '{}'::jsonb), ARRAY[p_view],
          COALESCE(preview_history->p_view, '[]'::jsonb) || to_jsonb(preview_images->>p_view))
        ELSE COALESCE(preview_history, '{}'::jsonb)
      END,
      preview_images = COALESCE(preview_images, '{}'::jsonb) || jsonb_build_object(p_view, p_url),
      preview_image_url = CASE WHEN p_view = 'sklep' OR preview_image_url IS NULL THEN p_url ELSE preview_image_url END,
      updated_at = now()
  WHERE id = p_session
  RETURNING image_count;
$fn$;

CREATE OR REPLACE FUNCTION public.bud_costs_daily(p_from date, p_to date)
RETURNS TABLE(day date, kind text, cost_usd numeric, calls bigint)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $fn$
  SELECT (created_at AT TIME ZONE 'Europe/Warsaw')::date AS day,
         kind, SUM(cost_usd) AS cost_usd, COUNT(*) AS calls
  FROM bud_usage
  WHERE (created_at AT TIME ZONE 'Europe/Warsaw')::date BETWEEN p_from AND p_to
  GROUP BY 1, 2 ORDER BY 1;
$fn$;

CREATE OR REPLACE FUNCTION public.bud_session_costs()
RETURNS TABLE(session_id uuid, cost_usd numeric, input_tokens bigint, cached_tokens bigint, output_tokens bigint, images bigint, calls bigint)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $fn$
  SELECT session_id, SUM(cost_usd), SUM(input_tokens)::bigint, SUM(cached_tokens)::bigint,
         SUM(output_tokens)::bigint, SUM(images)::bigint, COUNT(*)::bigint
  FROM bud_usage GROUP BY session_id;
$fn$;

CREATE OR REPLACE FUNCTION public.bud_session_avatars()
RETURNS TABLE(auth_user_id uuid, avatar_url text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public', 'auth' AS $fn$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.team_members tm WHERE tm.user_id = auth.uid()) THEN
    RETURN;
  END IF;
  RETURN QUERY
    SELECT DISTINCT s.auth_user_id, (u.raw_user_meta_data->>'avatar_url')
    FROM public.bud_sessions s
    JOIN auth.users u ON u.id = s.auth_user_id
    WHERE s.auth_provider = 'google'
      AND (u.raw_user_meta_data->>'avatar_url') IS NOT NULL;
END;
$fn$;

-- ----------------------------------------------------------------------------
-- E. RLS (enable + polityki: admin = team_members, owner = auth_user_id)
-- ----------------------------------------------------------------------------
ALTER TABLE public.bud_sessions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bud_messages          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bud_usage             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bud_reveals           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bud_emails            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bud_abandoned_emails  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bud_sms               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bud_short_links       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bud_feedback          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bud_knowhow_items     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bud_knowhow_summary   ENABLE ROW LEVEL SECURITY;

-- bud_sessions: owner SELECT + admin SELECT/UPDATE (brak INSERT/DELETE dla authenticated -> service_role)
DROP POLICY IF EXISTS bud_sessions_owner_select ON public.bud_sessions;
CREATE POLICY bud_sessions_owner_select ON public.bud_sessions FOR SELECT TO authenticated
  USING (auth_user_id = auth.uid());
DROP POLICY IF EXISTS bud_sessions_admin_read ON public.bud_sessions;
CREATE POLICY bud_sessions_admin_read ON public.bud_sessions FOR SELECT TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members));
DROP POLICY IF EXISTS bud_sessions_admin_update ON public.bud_sessions;
CREATE POLICY bud_sessions_admin_update ON public.bud_sessions FOR UPDATE TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members))
  WITH CHECK (auth.uid() IN (SELECT user_id FROM public.team_members));

-- bud_messages: tylko admin SELECT (klient czyta przez edge owner-gate)
DROP POLICY IF EXISTS bud_messages_admin_read ON public.bud_messages;
CREATE POLICY bud_messages_admin_read ON public.bud_messages FOR SELECT TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members));

-- pozostałe: tylko admin SELECT
DROP POLICY IF EXISTS bud_usage_admin_read ON public.bud_usage;
CREATE POLICY bud_usage_admin_read ON public.bud_usage FOR SELECT TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members));
DROP POLICY IF EXISTS bud_reveals_admin_read ON public.bud_reveals;
CREATE POLICY bud_reveals_admin_read ON public.bud_reveals FOR SELECT TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members));
DROP POLICY IF EXISTS bud_emails_admin_read ON public.bud_emails;
CREATE POLICY bud_emails_admin_read ON public.bud_emails FOR SELECT TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members));
DROP POLICY IF EXISTS bud_abandoned_admin_read ON public.bud_abandoned_emails;
CREATE POLICY bud_abandoned_admin_read ON public.bud_abandoned_emails FOR SELECT TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members));
DROP POLICY IF EXISTS bud_sms_admin_read ON public.bud_sms;
CREATE POLICY bud_sms_admin_read ON public.bud_sms FOR SELECT TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members));
DROP POLICY IF EXISTS bud_short_links_admin_read ON public.bud_short_links;
CREATE POLICY bud_short_links_admin_read ON public.bud_short_links FOR SELECT TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members));
DROP POLICY IF EXISTS bud_feedback_admin_read ON public.bud_feedback;
CREATE POLICY bud_feedback_admin_read ON public.bud_feedback FOR SELECT TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members));

-- bud_knowhow_items: owner (created_by) + admin (mirror spar)
DROP POLICY IF EXISTS bki_admin_read ON public.bud_knowhow_items;
CREATE POLICY bki_admin_read ON public.bud_knowhow_items FOR SELECT TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members));
DROP POLICY IF EXISTS bki_owner_read ON public.bud_knowhow_items;
CREATE POLICY bki_owner_read ON public.bud_knowhow_items FOR SELECT TO authenticated
  USING (created_by = auth.uid());
DROP POLICY IF EXISTS bki_owner_insert ON public.bud_knowhow_items;
CREATE POLICY bki_owner_insert ON public.bud_knowhow_items FOR INSERT TO authenticated
  WITH CHECK ((created_by = auth.uid()) AND (source_tag = 'klient'));
DROP POLICY IF EXISTS bki_admin_insert ON public.bud_knowhow_items;
CREATE POLICY bki_admin_insert ON public.bud_knowhow_items FOR INSERT TO authenticated
  WITH CHECK (auth.uid() IN (SELECT user_id FROM public.team_members));
DROP POLICY IF EXISTS bki_owner_update ON public.bud_knowhow_items;
CREATE POLICY bki_owner_update ON public.bud_knowhow_items FOR UPDATE TO authenticated
  USING (created_by = auth.uid())
  WITH CHECK ((created_by = auth.uid()) AND (source_tag = 'klient'));
DROP POLICY IF EXISTS bki_admin_update ON public.bud_knowhow_items;
CREATE POLICY bki_admin_update ON public.bud_knowhow_items FOR UPDATE TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members))
  WITH CHECK (auth.uid() IN (SELECT user_id FROM public.team_members));
DROP POLICY IF EXISTS bki_admin_del ON public.bud_knowhow_items;
CREATE POLICY bki_admin_del ON public.bud_knowhow_items FOR DELETE TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members));

-- bud_knowhow_summary: admin + owner read
DROP POLICY IF EXISTS bks_admin_read ON public.bud_knowhow_summary;
CREATE POLICY bks_admin_read ON public.bud_knowhow_summary FOR SELECT TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members));
DROP POLICY IF EXISTS bks_owner_read ON public.bud_knowhow_summary;
CREATE POLICY bks_owner_read ON public.bud_knowhow_summary FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.bud_sessions s WHERE s.id = bud_knowhow_summary.session_id AND s.auth_user_id = auth.uid()));
DROP POLICY IF EXISTS bks_admin_insert ON public.bud_knowhow_summary;
CREATE POLICY bks_admin_insert ON public.bud_knowhow_summary FOR INSERT TO authenticated
  WITH CHECK (auth.uid() IN (SELECT user_id FROM public.team_members));
DROP POLICY IF EXISTS bks_admin_update ON public.bud_knowhow_summary;
CREATE POLICY bks_admin_update ON public.bud_knowhow_summary FOR UPDATE TO authenticated
  USING (auth.uid() IN (SELECT user_id FROM public.team_members))
  WITH CHECK (auth.uid() IN (SELECT user_id FROM public.team_members));

-- ----------------------------------------------------------------------------
-- F. GRANTY (mirror spar_*; bud_sessions UPDATE tylko kolumnowy dla panelu)
-- ----------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON
  public.bud_sessions, public.bud_messages, public.bud_usage, public.bud_reveals,
  public.bud_emails, public.bud_abandoned_emails, public.bud_sms, public.bud_short_links,
  public.bud_feedback, public.bud_knowhow_items, public.bud_knowhow_summary
  TO anon, authenticated, service_role;

-- bud_sessions: authenticated NIE może updatować dowolnych kolumn (tylko panelowe)
REVOKE UPDATE, DELETE ON public.bud_sessions FROM authenticated;
GRANT UPDATE (is_test, showcase, hidden_from_feed, pipeline_override, idea_source, track)
  ON public.bud_sessions TO authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.bud_costs_daily(date,date)        TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.bud_session_costs()               TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.bud_session_avatars()             TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.bud_claim_lock(uuid,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.bud_release_lock(uuid,text)       TO service_role;
GRANT EXECUTE ON FUNCTION public.bud_record_image(uuid,text,text)  TO service_role;

-- ----------------------------------------------------------------------------
-- G. ALTER istniejących (additive, bezpieczne)
-- ----------------------------------------------------------------------------
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS bud_session_id uuid;
CREATE INDEX IF NOT EXISTS idx_orders_bud_session ON public.orders(bud_session_id);
-- leads.lead_source = wolny tekst (brak CHECK) -> 'budowanie' przejdzie bez zmian.
